// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtImW98XMKrP28Ffbcjrdd0AlIrjW7iNI',
    appId: '1:215972147797:web:858fc27ad932089bbbdadc',
    messagingSenderId: '215972147797',
    projectId: 'vssstudiostudyhour',
    authDomain: 'vssstudiostudyhour.firebaseapp.com',
    storageBucket: 'vssstudiostudyhour.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZOPx3eyEpg-uszsvNoyffSVzPam_its',
    appId: '1:215972147797:android:5becc3e8d86d5168bbdadc',
    messagingSenderId: '215972147797',
    projectId: 'vssstudiostudyhour',
    storageBucket: 'vssstudiostudyhour.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVbRwIYc_QFo1fGlz4eTqt7fSB07hoDjU',
    appId: '1:215972147797:ios:304c80e28d367b64bbdadc',
    messagingSenderId: '215972147797',
    projectId: 'vssstudiostudyhour',
    storageBucket: 'vssstudiostudyhour.firebasestorage.app',
    iosBundleId: 'com.example.studyHoursFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVbRwIYc_QFo1fGlz4eTqt7fSB07hoDjU',
    appId: '1:215972147797:ios:304c80e28d367b64bbdadc',
    messagingSenderId: '215972147797',
    projectId: 'vssstudiostudyhour',
    storageBucket: 'vssstudiostudyhour.firebasestorage.app',
    iosBundleId: 'com.example.studyHoursFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtImW98XMKrP28Ffbcjrdd0AlIrjW7iNI',
    appId: '1:215972147797:web:d512d64522962ffabbdadc',
    messagingSenderId: '215972147797',
    projectId: 'vssstudiostudyhour',
    authDomain: 'vssstudiostudyhour.firebaseapp.com',
    storageBucket: 'vssstudiostudyhour.firebasestorage.app',
  );

}